Fixed bug where a different algorithm throws
ranisalt/node-argon2 pull request #336
Opened 2022-02-12 07:27 UTC by franciscop

If used a different algorithm, the script will correctly deserialize but then fail to destructure `params: { m, t, p, data }` as seen in this bug:

```
TypeError: Cannot read property 'm' of undefined
    at Object.verify ([PATH]/node_modules/argon2/argon2.js:57:41)
    at file://[PATH]/src/register.js:72:35
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async [PATH]/node_modules/server/src/join/index.js:47:23
    at async [PATH]/node_modules/server/router/generic.js:28:5
    at async Object.middle ([PATH]/node_modules/server/src/join/index.js:47:23) {
  code: '',
  params: [Object: null prototype] { '0': '' }
}
```

With this PR I'd like to start a conversation on how to fix it, my proposal is to check for the algorithm used but we could also just check if `params` is there, or give `params` a default alternatively.

2022-02-12 13:22 UTC, ranisalt requested changes
Thanks! Looking forward to merging it, just a few mostly cosmetic changes to go.

2022-02-12 13:22 UTC, ranisalt commented on argon2.js
> +  if (!['argon2i', 'argon2d', 'argon2id'].includes(obj.id)) {
You could use `if (!(obj.id in types)`, `types` is defined as `{ argon2d: 0, argon2i: 1, argon2id: 2 }` and avoids duplicating data.

2022-02-12 13:22 UTC, ranisalt commented on argon2.js
> +  }
Please add a newline here, between `}` and `const ...` below

2022-02-12 13:23 UTC, ranisalt commented on argon2.js
> +  if (!['argon2i', 'argon2d', 'argon2id'].includes(obj.id)) {
```suggestion
  if (!(obj.id in types)) {
```

2022-02-12 13:23 UTC, ranisalt commented on argon2.js
> +  }
```suggestion
  }

```

2022-02-15 12:23 UTC, franciscop commented
I'm not sure why this test is failing, some CodacyCoverageReporter error, is it possible it's a fluke? Could you please try re-running the tests, @ranisalt ? The logs say this which I find strange since it was working earlier:

```
error [CodacyCoverageReporter] Invalid configuration: Either a project or account API token must be provided or available in an environment variable  - (CodacyCoverageReporter.scala:25)

 --> Failed!
Error: Process completed with exit code 1.
``

2022-02-15 17:12 UTC, ranisalt commented
Don't worry, Codacy is broken

2022-02-15 17:13 UTC, merged